--INSERT INTO CONTENT_TYPES(DESCRIPTION) VALUES('H1')
--INSERT INTO CONTENT_TYPES(DESCRIPTION) VALUES('P')
--INSERT INTO CONTENT_TYPES(DESCRIPTION) VALUES('H2')
--
--INSERT INTO CONTENT_PAGES(ID) VALUES(1)
--
--INSERT INTO CONTENTS(DATA, TYPE_ID, PAGE_ID) VALUES('H1 MUITO LEGAL', 1, 1)
--INSERT INTO CONTENTS(DATA, TYPE_ID, PAGE_ID) VALUES('P MUITO LEGAL', 2, 1)
--INSERT INTO CONTENTS(DATA, TYPE_ID, PAGE_ID) VALUES('H2 MUITO LEGAL', 3, 1)

